# Custom Language File for Launcher Customizer

[ejs.app]
title = "Elkube Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/LiveInGround/Elkube-Launcher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://elkube.wtfcraft.ovh/communitytube"
mediaDiscordURL = "https://elkube.wtfcraft.ovh/discord"

[ejs.settings]
sourceGithubLink = "https://github.com/LiveInGround/Elkube-Launcher"
supportLink = "https://github.com/LiveInGround/Elkube-Launcher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR ELKUBE !"
welcomeDescription = "Bienvenue sur Elkube (v2), un serveur SMP mod√© 1.20.1 sur des √Æles flottantes uniques. Explore le Cryoveth ‚ùÑÔ∏è, un monde glac√© aux ressources rares, affronte le Pyroveth üåã, un monde volcanique et dangereux, ou b√¢tis librement dans l‚ÄôAetheris ‚ú®, le monde mystique o√π les minerais rares sont pr√©cieux. Chaque monde est compos√© d'√Æles flottantes, et offre d√©fis et aventures uniques pour les explorateurs, b√¢tisseurs et aventuriers en qu√™te de sensations fortes."
welcomeDescCTA = "Vous √™tes juste √† quelques clics d'Elkube."
